

-- Générer les commandes CREATE TABLE (reconstruction)
SELECT 
    n.nspname as schema_name,
    c.relname as table_name,
    'CREATE TABLE ' || n.nspname || '.' || c.relname || E' (\n' ||
    STRING_AGG(
        '    ' || a.attname || ' ' || 
        format_type(a.atttypid, a.atttypmod) ||
        CASE 
            WHEN a.attnotnull THEN ' NOT NULL'
            ELSE ''
        END ||
        CASE 
            WHEN a.attidentity = 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
            WHEN a.attidentity = 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
            ELSE ''
        END ||
        CASE 
            WHEN pg_get_expr(ad.adbin, ad.adrelid) IS NOT NULL THEN 
                ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid)
            ELSE ''
        END,
        E',\n'
    ) ||
    COALESCE(
        E',\n' || (
            SELECT STRING_AGG(
                '    CONSTRAINT ' || conname || ' ' || 
                pg_get_constraintdef(oid),
                E',\n'
            )
            FROM pg_constraint 
            WHERE conrelid = c.oid 
            AND contype IN ('p', 'u', 'c')
        ),
        ''
    ) ||
    E'\n);' as create_statement
FROM pg_class c
JOIN pg_namespace n ON c.relnamespace = n.oid
JOIN pg_attribute a ON c.oid = a.attrelid
LEFT JOIN pg_attrdef ad ON a.attrelid = ad.adrelid AND a.attnum = ad.adnum
WHERE c.relkind = 'r'
AND n.nspname NOT IN ('pg_catalog', 'information_schema')
AND a.attnum > 0
AND NOT a.attisdropped
GROUP BY n.nspname, c.relname, c.oid
ORDER BY n.nspname, c.relname;